- name: install dependencies
  become: true
  apt:
    name:
      - python3
      - python3-pip
      - python3-dev
      - python3-setuptools
      - python-pip
      - python-setuptools
      - libffi-dev
      - libssl-dev
